services:
  - type: web
    name: transiq-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Backend/Dockerfile
    dockerContext: ./Backend
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
    healthCheckPath: /actuator/health
